In [1]:
import numpy as np

In [2]:
nums=np.array([1, 3, 5, 7, 9])
print(nums)

[1 3 5 7 9]


In [6]:
nums_plus_2=nums+2
print(nums_plus_2)

[ 3  5  7  9 11]


In [7]:
nums_plus_2*3

array([ 9, 15, 21, 27, 33])

In [12]:
num_sum=np.sum(nums)
print(num_sum)

25


In [13]:
num_max=np.max(nums)
print(num_max)

9


In [14]:
num_mean=np.mean(nums)
print(num_mean)

5.0
